### ISSUE TITLE
Task 6 - Button for read books

### ISSUE THREAD

**Issue by DoroVernier** [DoroVernier/capstone-project#10]
**Value Proposition**
As a user I need another button to be able to separate the book-cards of the books that I have only read but not bought from those that are still on the wish-list 

**Description**
![CSP_Wf_5](https://user-images.githubusercontent.com/109967704/191221642-2aa44f05-9404-4faf-afcd-9a03383d8998.png)

**Acceptance Criteria**
- [ ]  with a click on a button, any card from the wish-list can be moved to a separate area
- [ ] the separate Area, which contains the books that I have physically bought is named My physical bookshelf
- [ ]  no alert is shown upon clicking the button...

**Tasks**

- [ ]  create a new button on each card
- [ ] add header for My future bookshelf
- [ ] add area for the moved cards
- [ ] add logic to move the book-cards
