### ISSUE TITLE
Task 7 - read-icon

### ISSUE THREAD

**Issue by DoroVernier** [DoroVernier/capstone-project#14]
**Value Proposition**
As a reader I need a read-icon to be able to mark the books that I have read

**Description**
![CSP_WF_8](https://user-images.githubusercontent.com/109967704/192508498-b5739181-c3c4-4ed2-b9fa-2cc4298320a0.png)

**Acceptance Criteria**
- [x]  every card starts off with a unread-icon (closed eye)
- [x] when the icon is clicked, it changes to read (open eye)...
- [x] by clicking again, the icon changes back to unread

**Tasks**
- [x]  add bookmark icons to record files
- [x]  write logic to toggle the icon between read and unread...
