### ISSUE TITLE
API

### ISSUE THREAD

**Issue by DoroVernier** [DoroVernier/capstone-project#16]
**Value Proposition**
As a user
I need access to external sources
to be able to see information about the book on display.

**Description**
![Bildschirmfoto 2022-09-29 um 15 50 26](https://user-images.githubusercontent.com/109967704/193050953-77355abe-dcab-46c5-96d6-d7a55f0a76db.png)

**Acceptance Criteria**
- [x] a new card is rendered containing book-title, author and book-cover
- [x]  Information on the book is accessed by submitting the isbn

**Tasks**
 e.g. Components, Storybook, testing
- [x]  connect API 
- [x] write logic to render information

**Comment by MerleMak** [comment]
great :)
