### ISSUE TITLE
ISBN - Input

### ISSUE THREAD

**Issue by DoroVernier** [DoroVernier/capstone-project#18]
**Value Proposition**
As a user
I need feedback 
to be able to recognise if my input is not a valid ISBN

**Description**
![Bildschirmfoto 2022-10-04 um 20 38 59](https://user-images.githubusercontent.com/109967704/193899283-dc58781a-70bd-4197-93c7-3e92dcb17d86.png)

**Acceptance Criteria**

- [x]  When the input value is not a valid ISBN, a message alerts the user accordingly...

**Tasks**

- [x]  write logic to only accept valid ISBNs as Input
- [x] style the message ...
