### ISSUE TITLE
Taks 1 - input field & rendering of input

### ISSUE THREAD

**Issue by DoroVernier** [DoroVernier/capstone-project#2]
**Value Proposition**

As a reader 
I need to note down book recommendations 
to be able to remember and access them later.

**Description**

![Bildschirmfoto 2022-09-14 um 15 14 36](https://user-images.githubusercontent.com/109967704/190163987-e12d2985-5f99-420f-8d30-45f55d01b206.png)

**Acceptance Criteria**

- [x]  When clicking into the input field, any text can be written.
- [x] Upon clicking on the submit button, a new book-card appears
- [x] When clicking on the submit-button without any content in the input-field, an alert appears, notifying the user that input is required
- [ ] whitespaces are not transfered to the cards

**Tasks**

- [x] create a new project with `npx create-next-app@latest`
- [x] create a branch
- [x] create a `<h1>` with "Future Bookshelf"
- [x] create an unordered list with the book-cards als list-elements
- [x] create a form with a required input field and a submit button
- [x] write logic for rendering the input as book-cards (including a state)
- [ ] before input is put into the state, it is trimmed to avoid whitespaces
- [x] set a max length for the input

**Comment by MerleMak** [comment]
Hi Doro, 
great first User Story, I like the Value Proposition!
I have two things:
1. your last point of the acceptance criteria is a counter, which you then didn't include into the tasks. I would recommend to put this criteria into another User Story, to keep this one slim. 
2. characters is spelled with a c :P

Good Job otherwise! :)
