### ISSUE TITLE
Book Cover - image

### ISSUE THREAD

**Issue by DoroVernier** [DoroVernier/capstone-project#20]
**Value Proposition**
As a user
I need the image of the book-cover on my book cards
to be able to remember and recognise the book easier and faster

**Description**
![Bildschirmfoto 2022-10-06 um 10 09 07](https://user-images.githubusercontent.com/109967704/194257733-b9023ea6-6b3c-450f-9ad1-e06933d383bb.png)

**Acceptance Criteria**
- [x]  when the card is rendered, it shows title, author and cover image

**Tasks**
- [x]  get the image of the book cover from the google books api
- [x] render the image on the card
