### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by DoroVernier** [DoroVernier/capstone-project#25]
**Value Proposition**
As a user
I need an updated input field
to be able to search for titles, authors or keywords

**Description**
<img width="363" alt="Bildschirmfoto 2022-10-09 um 11 22 00" src="https://user-images.githubusercontent.com/109967704/194748773-c5fb5b0c-aae6-4445-b675-dbd3576f2daf.png">

**Acceptance Criteria**
- [ ]  the inputfield accepts a query for ISBN, author, title or keyword
- [ ] in a drop-down field, 3 results are provided
- [ ] upon choosing one of the three results, a new card with that book is rendered...

**Tasks**
- [ ]  change search-options logic
- [ ] provide space for results
- [ ] change label 
- [ ] change placeholder...
