### ISSUE TITLE
Task 2 - Character Counter

### ISSUE THREAD

**Issue by DoroVernier** [DoroVernier/capstone-project#3]
**Value Proposition**
As a user 
I need to see and know, how many characters I have written and, respectively, how much space I have left to write
to be able to actually submit the text. 

**Description**
![CSP_Wf_2](https://user-images.githubusercontent.com/109967704/190379023-e9fa8962-6402-43f7-8088-1e66cbb37846.png)

**Acceptance Criteria**
 - [x]  the counter shows two values: how many characters are written in the input-field and how many characters are possible to be written
 - [x] the value of how many characters **can** be written stays fixed at 70. 
 - [x] the value how many characters **are** written goes up by one with every keystroke that adds a character until the maximum number is reached.
 - [x] when characters are deleted, the counter of written characters goes down by one for each character deleted 

**Tasks**
 - [x] create counter close to input-field as an HTML `output`element
 - [x] write logic using an event-listener, listening to the keystrokes

**Comment by ben-me** [comment]
Good user story.

> the two values count with every characters that is written: +1 for written characters, -1 for characters left <

I think it might be confusing to go from 0/70 to 1/69 to 2/68 and so on. Might be better to have the max number unchanged so you see 12/70 instead of 12/58. But that's just a design/personal choice.

> [ ] create counter close to input-field as an output-field

What do you mean with output field?
And what kind of event listener are you referring to? What should he listen to and where?
