### ISSUE TITLE
Task 3 - Delete Buttons

### ISSUE THREAD

**Issue by DoroVernier** [DoroVernier/capstone-project#4]
**Value Proposition**
As a user I need a delete-button to be able to remove book-cards when necessary.

**Description**
![CSP_Wf_3](https://user-images.githubusercontent.com/109967704/190384186-9a952da2-f5c9-465e-987f-9415da2c9523.png)

**Acceptance Criteria**
- [x] each card has a remove-button
- [x] the button reacts promptly, without prior warning 

**Tasks**
- [x]  create button-component
- [x] write logic to delete element using onClick

**Comment by K-Juno** [comment]
Simple and effective. ;) Happy Coding!
