### ISSUE TITLE
Task 4 - Move function

### ISSUE THREAD

**Issue by DoroVernier** [DoroVernier/capstone-project#5]
**Value Proposition**
As a user I need a move-button to be able to separate the book-cards of the books that I have physically bought from those that are still on the wish-list

**Description**
![CSP_Wf_5](https://user-images.githubusercontent.com/109967704/191221642-2aa44f05-9404-4faf-afcd-9a03383d8998.png)

**Acceptance Criteria**
- [ ]  with a click on a button, any card from the wish-list can be moved to a separate area
- [ ] the separate Area, which contains the books that I have physically bought is named My physical bookshelf
- [ ]  no alert is shown upon clicking the button...

**Tasks**

- [ ]  create a new button on each card
- [ ] add header for My future bookshelf
- [ ] add area for the moved cards
- [ ] add logic to move the book-cards

**Comment by AnH13-6** [comment]
Hi Doro! You seem to be working on an interesting app! :) 
The only thing you might reconsider is dividing this step into two features as it seems to be a lot of code for just one. 
Feature 1 could be adding the button and function, feature 2 adding the new page.

**Comment by StefanieLoeser** [comment]
Looking very good so far! 
Just maybe is it possible that some features that you moved to the next user story are still in this ones? Do you need to create an area for the moved-cards when in the next step you create a new page and move the cards there? Maybe you can save the first step.
