### ISSUE TITLE
Task 6- Nav Bar

### ISSUE THREAD

**Issue by DoroVernier** [DoroVernier/capstone-project#6]
**Value Proposition**
As a user I need a navigation bar to be able to switch between the pages

**Description**
![CSP_Wf_7](https://user-images.githubusercontent.com/109967704/192504872-9591e4de-a77c-4ea7-973d-cb36b9c91a5d.png)

**Acceptance Criteria**
- [ ]  fixed navigation bar at the bottom of the page
- [ ] visible and accessible on both pages
- [ ] nav-bar is split into two fields, one for each page
- [ ] active field is highlighted
- [ ] when clicking on the non-active field, the page is changed ...

**Tasks**

- [ ]  add nav-bar-component
- [ ] add logic for nav-bar...

**Comment by K-Juno** [comment]
Pretty clear goal, good job!
