### ISSUE TITLE
Task 5 - New page

### ISSUE THREAD

**Issue by DoroVernier** [DoroVernier/capstone-project#7]
**Value Proposition**
As a user I need a separate page to be able to display the books that I have bought from those that are still on my wish-list

**Description**
![CSP_Wf_6](https://user-images.githubusercontent.com/109967704/191224145-3df32801-52b4-4a0a-8bfe-4e32cae7e17c.png)

**Acceptance Criteria**
- [ ] when clicking on the move-button, the card moves to a new page
- [ ]  no alert is given
- [ ] the user stays on the original page ...

**Tasks**
- [ ]  create new page, called "My bookshelf"
- [ ] adjust logic to move the cards to a new page instead of to another area...
